Models/Department.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagmentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Manager { get; set; }
    }
}

Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FactoryManagmentWeb.Models;

namespace FactoryManagmentWeb.Controllers
{
    public class DepartmentController : Controller
    {
        static DepartmentBL departmentBL = new DepartmentBL();

        static EmployeeBL employeeBL = new EmployeeBL();

        static UserAccessBL userAccessBL = new UserAccessBL();

        static UserBL userBL = new UserBL();

        // GET: Department
        public ActionResult Index()
        {
            if ((bool)Session["authenticated"] == true && (int)Session["numOfAction"] > 0)
            {
                ///update number of actions
                var userID = (int)Session["userID"];

                var userAcc = userAccessBL.GetUserAccess(userID);
                Session["numOfAction"] = userAcc.NumOfActions -1;
                userAccessBL.UpdateUserAccessNum(userAcc);
                userBL.UpdateUserNumOfAction(userID);


                ViewBag.fullname = Session["fullname"];

                var departmentsList = departmentBL.GetDepartments();
                ViewBag.departments = departmentsList;

                var employeesList = employeeBL.GetEmployees();
                ViewBag.employees = employeesList;

                return View("Departments");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

        public ActionResult EditDepartment(int id)
        {
            if ((bool)Session["authenticated"] == true && (int)Session["numOfAction"] > 0)
            {
                ViewBag.fullname = Session["fullname"];

                var userID = (int)Session["userID"];

                var userAcc = userAccessBL.GetUserAccess(userID);
                Session["numOfAction"] = userAcc.NumOfActions - 1;
                userAccessBL.UpdateUserAccessNum(userAcc);
                userBL.UpdateUserNumOfAction(userID);


                Department dep = departmentBL.GetDepartments(id);
                return View("EditDepartment",dep);
               
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

        [HttpPost]
        public ActionResult GetUpdateDepartmentFromUser(Department dep)
        {
            if ( (bool)Session["authenticated"] == true && (int)Session["numOfAction"] > 0)
            {
                ViewBag.fullname = Session["fullname"];
                
                departmentBL.UpdateDepartment(dep);
                return RedirectToAction("Index");
 
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

        public ActionResult DeleteDepartment(int id)
        {
            if ( (bool)Session["authenticated"] == true && (int)Session["numOfAction"] > 0)
            {
                ViewBag.fullname = Session["fullname"];
                
                departmentBL.DeleteDepartment(id);
                return RedirectToAction("Index");

            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

        [HttpPost]
        public ActionResult GetNewDepartmentFromUser(Department dep)
        {
            if ( (bool)Session["authenticated"] == true && (int)Session["numOfAction"] > 0)
            {
                ViewBag.fullname = Session["fullname"];
        
                departmentBL.AddDepartment(dep);
                return RedirectToAction("Index");
 
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

        public ActionResult AddDepartment()
        {
            if ( (bool)Session["authenticated"] == true && (int)Session["numOfAction"] > 0)
            {
                ViewBag.fullname = Session["fullname"];

                var userID = (int)Session["userID"];

                var userAcc = userAccessBL.GetUserAccess(userID);
                Session["numOfAction"] = userAcc.NumOfActions - 1;
                userAccessBL.UpdateUserAccessNum(userAcc);
                userBL.UpdateUserNumOfAction(userID);



                return View("NewDepartment");

            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }
    }
}

Views/Department/Departments.cshtml
@{
    Layout = null;
    bool flag = false;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Departments</title>
</head>
<body>
    <div>
        <h3 style="color :red" >Hello @ViewBag.fullname</h3>
        <h4>@Html.ActionLink("Log-Out", "LogOut", "Login")</h4>
    </div>
    <div style=" text-align:center " > 
        <h3>Deparments List</h3>

        <table style="margin-left:auto;margin-right:auto;">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Manager</th>
                </tr>
            </thead>
            @foreach (var item in ViewBag.departments)
            {
        <tr>
            <td>@item.ID</td>
            <td>@item.Name</td>
            <td>@item.Manager</td>
            <td>@Html.ActionLink("Edit", "EditDepartment", new { id = item.ID })</td>

            @foreach (var emp in ViewBag.employees)
            {
                if (emp.DepartmentID == item.ID)
                {
                    flag = false;
                    break;
                }
                else
                {
                    flag = true;
                    continue;
                }

            }
            @if (flag)
            {
                <td>@Html.ActionLink("Delete", "DeleteDepartment", new { id = item.ID })</td>
            }

        </tr>
            }

        </table>

        <h4>@Html.ActionLink("Add Department", "AddDepartment")</h4>


    </div>
    <div>
        <h4>@Html.ActionLink("Back", "Home", "Login")</h4>
    </div>
</body>
</html>

Views/Department/EditDepartment.cshtml
@model FactoryManagmentWeb.Models.Department
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EditDepartment</title>
</head>
<body>
    <div>
        <h3 style="color :red">Hello @ViewBag.fullname</h3>
        <h4>@Html.ActionLink("Log-Out", "LogOut", "Login")</h4>
    </div>
    <div>
        <h3> Edit Department</h3>

        <form action="/Department/GetUpdateDepartmentFromUser" method="post">
            ID:@Html.EditorFor(x => x.ID)<br />
            Department Name: @Html.EditorFor(x => x.Name)<br />
            Manager ID: @Html.EditorFor(x => x.Manager)<br />
            <input type="submit" value="Update" />
        </form>
    </div>
    <div>
        <h4>@Html.ActionLink("Back", "Index", "Department")</h4>
    </div>
</body>
</html>

Views/Department/NewDepartment.cshtml
@model FactoryManagmentWeb.Models.Department
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>NewDepartment</title>
</head>
<body>
    <div>
        <h3 style="color :red">Hello @ViewBag.fullname</h3>
        <h4>@Html.ActionLink("Log-Out", "LogOut", "Login")</h4>
    </div>
    <div>
        <h3> Add Department</h3>

        <form action="/Department/GetNewDepartmentFromUser" method="post">
            ID:@Html.TextBoxFor(x => x.ID)<br />
            Department Name: @Html.TextBoxFor(x => x.Name)<br />
            Manager ID: @Html.TextBoxFor(x => x.Manager)<br />
            <input type="submit" value="Save" />
        </form>
    </div>
    <div>
        <h4>@Html.ActionLink("Back", "Index", "Department")</h4>
    </div>
</body>
</html>