Models/Shift.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryManagmentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int StartTime { get; set; }
        public int EndTime { get; set; }
    }
}

Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FactoryManagmentWeb.Models;

namespace FactoryManagmentWeb.Controllers
{
    public class EmployeeController : Controller
    {
        static EmployeeBL employeeBL = new EmployeeBL();
        
        static EmployeeShiftBL employeeShiftBL = new EmployeeShiftBL();
        static DepartmentBL departmentBL = new DepartmentBL();
        static ShiftBL shiftBL = new ShiftBL();

        static UserAccessBL userAccessBL = new UserAccessBL();
        static UserBL userBL = new UserBL();


        // GET: Employee
        public ActionResult Index()
        {
            if( (bool)Session["authenticated"] == true && (int)Session["numOfAction"] > 0)
            {
                var userID = (int)Session["userID"];

                var userAcc = userAccessBL.GetUserAccess(userID);
                Session["numOfAction"] = userAcc.NumOfActions - 1;
                userAccessBL.UpdateUserAccessNum(userAcc);
                userBL.UpdateUserNumOfAction(userID);

                ViewBag.fullname = Session["fullname"];

                var employeesList = employeeBL.GetEmployees();
                ViewBag.employees = employeesList;

                var employeeShiftsList = employeeShiftBL.GetEmployeeShifts();
                ViewBag.employeesShift = employeeShiftsList;

                var shiftsList = shiftBL.GetShifts();
                ViewBag.shift = shiftsList;

                return View("Employees");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

        public ActionResult EditEmployee(int id)
        {
            if ((bool)Session["authenticated"] == true && (int)Session["numOfAction"] > 0)
            {
                var userID = (int)Session["userID"];

                var userAcc = userAccessBL.GetUserAccess(userID);
                Session["numOfAction"] = userAcc.NumOfActions - 1;
                userAccessBL.UpdateUserAccessNum(userAcc);
                userBL.UpdateUserNumOfAction(userID);

                ViewBag.fullname = Session["fullname"];

                var departmentsList = departmentBL.GetDepartments();
                ViewBag.Departments = departmentsList;

                Employee emp = employeeBL.GetEmployee(id);
                return View("EditEmployee", emp);

            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

        [HttpPost]
        public ActionResult GetUpdateEmployeeFromUser(Employee emp)
        {
            if (Session["authenticated"] != null && (bool)Session["authenticated"] == true)
            {
                ViewBag.fullname = Session["fullname"];
                employeeBL.UpdateEmployee(emp);
                return RedirectToAction("Index");

            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }


        public ActionResult AddShiftToEmployee( int id)
        {
            if ((bool)Session["authenticated"] == true && (int)Session["numOfAction"] > 0)
            {
                var userID = (int)Session["userID"];

                var userAcc = userAccessBL.GetUserAccess(userID);
                Session["numOfAction"] = userAcc.NumOfActions - 1;
                userAccessBL.UpdateUserAccessNum(userAcc);
                userBL.UpdateUserNumOfAction(userID);

                ViewBag.fullname = Session["fullname"];
                ViewBag.id = id;

                return View("AddShiftToEmployee");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

        [HttpPost]
        public ActionResult GetNewEmployeeShiftFromUser(EmployeeShift e)
        {
            if (Session["authenticated"] != null && (bool)Session["authenticated"] == true)
            {
                ViewBag.fullname = Session["fullname"];
                
                employeeShiftBL.AddShift(e);
                return RedirectToAction("Index");

            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
;
        }

        public ActionResult SearchEmployee()
        {
            if ((bool)Session["authenticated"] == true && (int)Session["numOfAction"] > 0)
            {
                var userID = (int)Session["userID"];

                var userAcc = userAccessBL.GetUserAccess(userID);
                Session["numOfAction"] = userAcc.NumOfActions - 1;
                userAccessBL.UpdateUserAccessNum(userAcc);
                userBL.UpdateUserNumOfAction(userID);

                ViewBag.fullname = Session["fullname"];

                return View("SearchResults");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

        [HttpPost]
        public ActionResult SearchResult(string phrase)
        {
            if ((bool)Session["authenticated"] == true && (int)Session["numOfAction"] > 0)
            {
                var userID = (int)Session["userID"];

                var userAcc = userAccessBL.GetUserAccess(userID);
                Session["numOfAction"] = userAcc.NumOfActions - 1;
                userAccessBL.UpdateUserAccessNum(userAcc);
                userBL.UpdateUserNumOfAction(userID);

                ViewBag.fullname = Session["fullname"];
               
                var result = employeeBL.Search(phrase);
                ViewBag.employee = result;
                return View("SearchResults");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

        public ActionResult DeleteEmployee(int id)
        {
            employeeBL.DeleteEmployee(id);
            return RedirectToAction("index");
        }
    }
}

Controllers/ShiftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FactoryManagmentWeb.Models;

namespace FactoryManagmentWeb.Controllers
{
    public class ShiftController : Controller
    {
        static EmployeeShiftBL employeeShiftBL = new EmployeeShiftBL();
        static EmployeeBL employeeBL = new EmployeeBL();

        static ShiftBL shiftBL = new ShiftBL();

        static UserAccessBL userAccessBL = new UserAccessBL();

        static UserBL userBL = new UserBL();
        // GET: Shift

        public ActionResult Index()
        {

            if ((bool)Session["authenticated"] == true && (int)Session["numOfAction"] > 0)
            {
                var userID = (int)Session["userID"];

                var userAcc = userAccessBL.GetUserAccess(userID);
                Session["numOfAction"] = userAcc.NumOfActions - 1;
                userAccessBL.UpdateUserAccessNum(userAcc);
                userBL.UpdateUserNumOfAction(userID);

                ViewBag.fullname = Session["fullname"];
                
                var shiftsList = shiftBL.GetShifts();
                ViewBag.shifts = shiftsList;

                var employeeShiftsList = employeeShiftBL.GetEmployeeShifts();
                ViewBag.employeesShift = employeeShiftsList;


                var employeeList = employeeBL.GetEmployees();
                ViewBag.employeeList = employeeList;

                return View("Shifts");

            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

        public ActionResult AddShift()
        {
            if ((bool)Session["authenticated"] == true && (int)Session["numOfAction"] > 0)
            {
                var userID = (int)Session["userID"];

                var userAcc = userAccessBL.GetUserAccess(userID);
                Session["numOfAction"] = userAcc.NumOfActions - 1;
                userAccessBL.UpdateUserAccessNum(userAcc);
                userBL.UpdateUserNumOfAction(userID);

                ViewBag.fullname = Session["fullname"];
                return View("AddShift");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }


        }

        [HttpPost]
        public ActionResult AddNewShift(Shift s)
        {
            if (Session["authenticated"] != null && (bool)Session["authenticated"] == true)
            {
                ViewBag.fullname = Session["fullname"];

                shiftBL.AddNewShift(s);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

    }
}

Views/Shift/AddShift.cshtml
@model FactoryManagmentWeb.Models.Shift
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddShift</title>
</head>
<body>
    <div>
        <h3 style="color :red">Hello @ViewBag.fullname</h3>
        <h4>@Html.ActionLink("Log-Out", "LogOut", "Login")</h4>
    </div>
    <div>
        <h3>Add New Shift</h3>


        <form action="/Shift/AddNewShift" method="post">
            Shift Date:@Html.TextBoxFor(x => x.Date)<br />
            Start Time:@Html.TextBoxFor(x => x.StartTime) <br />
            End Time:@Html.TextBoxFor(x => x.EndTime) <br />

            <input type="submit" value="Add Shift" />



        </form>
    </div>
    <div>
        <h4>@Html.ActionLink("Back", "Index", "Shift")</h4>
    </div>
</body>
</html>

Views/Shift/Shifts.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Shifts</title>
</head>
<body>
    <div>
        <h3 style="color :red">Hello @ViewBag.fullname</h3>
        <h4>@Html.ActionLink("Log-Out", "LogOut", "Login")</h4>
    </div>
    <div>
        <h3>Shifts List</h3>

        <table border="1">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Date</th>
                    <th scope="col">Strat Time</th>
                    <th scope="col">End Time</th>
                    <th scope="col">Employee Name</th>
                </tr>
            </thead>

            @foreach (var item in ViewBag.shifts)
            {
        <tr>
            <td>@item.ID</td>
            <td>@item.Date.ToString("dd/MM/yyyy")</td>
            <td>@item.StartTime</td>
            <td>@item.EndTime</td>
            @foreach (var x in ViewBag.employeesShift)
            {
                if (item.ID == x.ShiftID)
                {
                    foreach (var emp in ViewBag.employeeList)
                    {
                        if (x.EmployeeID == emp.ID)
                        {
                            <td>@Html.ActionLink((string)emp.FirstName, "EditEmployee", "Employee", new { id = x.EmployeeID }, null)</td>

                        }
                    }

                }

            }

        </tr>
            }

        </table>

        <h4>@Html.ActionLink("Add Shift", "AddShift")</h4>
    </div>
    <div>
        <h4>@Html.ActionLink("Back", "Home", "Login")</h4>
    </div>
</body>
</html>